on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches: 
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: macos-latest
            cpp_compiler: g++
            build_type: Debug
          - os: ubuntu-20.04
            cpp_compiler: g++
            build_type: Debug


    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Set build directory variable
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Build
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -G Ninja
        -S ${{ github.workspace }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        ${{ github.workspace }};
        cmake --build ${{ steps.strings.outputs.build-output-dir }};

#    - name: Linting
#      run:
#        clang-tidy .


#    - name: Tests
#      working-directory: ${{ steps.strings.outputs.build-output-dir }}/tests
#      run: ./tests
